on:
   push:
     branches: [ develop ]
   pull_request:
     branches: [ develop ]

jobs:
   build-and-publish:

     runs-on: ubuntu-latest

     steps:
     - uses: actions/checkout@v2
     - name: Install Dependencies
       run: npm install
       
     - uses: fabacab/jekyll-builder-for-github-pages-action@master
          with:
            secret_gh_pages_api_token: ${{ secrets.GH_PAGES_TOKEN }}
            